In [1]:
import pandas as pd 

df = pd.read_csv('traffic_analysis.csv')

# Display the first few rows of the dataframe
df.head()

/var/folders/kt/_bzbz3vd5qbcfjnt5vssmqxh0000gn/T/ipykernel_1983/979532559.py:3: DtypeWarning: Columns (12,13,18,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('traffic_analysis.csv')

,raw_row_number,date,time,location,lat,lng,geocode_source,beat,district,subject_age,...,trust_in_local_government,trust_in_local_government_rate,economic_diversity_index,hardship_index,median_household_income,poverty_rate,foreign_born,limited_english_proficiency,demographics,population
0,4,2012-01-01,01:00:00,108 LAMON AVE N,41.882072,-87.747829,SU,NaN,NaN,35.0,...,29600.0,39.844682,0.775025,85.469151,51826.851402,23.399157,10.704508,8.804414,5.533701,97671.110800
1,9,2012-01-01,01:00:00,430 STATE ST N,41.890322,-87.628217,GM,NaN,NaN,26.0,...,34700.0,39.185753,0.354411,3.402425,125101.326886,9.622478,18.181435,4.297681,66.267215,99292.486072
2,11,2012-01-01,01:00:00,4225 ARMITAGE AVE W,41.916806,-87.732301,GM,NaN,NaN,26.0,...,12900.0,53.921078,0.798612,77.967935,70459.881153,13.674981,34.878304,36.024369,9.575501,22644.717836
3,18,2012-01-01,03:00:00,1011 GARFIELD BLVD W,41.793582,-87.650526,GM,NaN,NaN,22.0,...,4800.0,27.250549,0.728528,93.089143,32084.861861,33.435182,5.675052,5.465415,1.005840,23160.939521
4,20,2012-01-01,02:00:00,13455 MACKINAW AVE S,41.650292,-87.542070,GM,NaN,NaN,21.0,...,2100.0,28.253638,0.802099,68.392927,61745.599215,9.820789,14.676821,11.130220,35.767045,8767.938562

In [2]:
# drop unnecessary columns
df = df.drop(columns=["raw_row_number", "time", "location", "lat", "lng", "geocode_source", "beat", "district", "subject_age", "subject_race", "subject_sex", "officer_race", "officer_sex", "officer_years_of_service", "type", "violation", "outcome", "search_conducted", "search_person", "search_vehicle", "raw_race", "raw_driver_race", "geometry"])
# Display the first few rows of the modified dataframe
df.head()

,date,citation_issued,community_area_id,community_area_name,drug_abuse,major_crime,public_crime,violent_crime,perceived_neighborhood_violence_rate,perceived_neighborhood_safety_rate,...,trust_in_local_government,trust_in_local_government_rate,economic_diversity_index,hardship_index,median_household_income,poverty_rate,foreign_born,limited_english_proficiency,demographics,population
0,2012-01-01,False,25.0,AUSTIN,887.076330,5212.931862,4142.0,1860.058140,39.271852,50.052980,...,29600.0,39.844682,0.775025,85.469151,51826.851402,23.399157,10.704508,8.804414,5.533701,97671.110800
1,2012-01-01,False,8.0,NEAR NORTH SIDE,107.618043,4637.132155,410.0,647.271573,31.535808,75.076345,...,34700.0,39.185753,0.354411,3.402425,125101.326886,9.622478,18.181435,4.297681,66.267215,99292.486072
2,2012-01-01,False,20.0,HERMOSA,17.999670,577.545123,257.0,150.146585,14.840824,57.122871,...,12900.0,53.921078,0.798612,77.967935,70459.881153,13.674981,34.878304,36.024369,9.575501,22644.717836
3,2012-01-01,False,68.0,ENGLEWOOD,155.143225,2069.136841,1908.0,802.609406,51.774635,36.410150,...,4800.0,27.250549,0.728528,93.089143,32084.861861,33.435182,5.675052,5.465415,1.005840,23160.939521
4,2012-01-01,False,55.0,HEGEWISCH,2.972177,252.080902,50.0,57.518202,36.200762,51.187100,...,2100.0,28.253638,0.802099,68.392927,61745.599215,9.820789,14.676821,11.130220,35.767045,8767.938562

In [3]:
df.columns

Index(['date', 'citation_issued', 'community_area_id', 'community_area_name',
       'drug_abuse', 'major_crime', 'public_crime', 'violent_crime',
       'perceived_neighborhood_violence_rate',
       'perceived_neighborhood_safety_rate', 'trust_in_law_enforcement',
       'trust_in_law_enforcement_rate', 'trust_in_local_government',
       'trust_in_local_government_rate', 'economic_diversity_index',
       'hardship_index', 'median_household_income', 'poverty_rate',
       'foreign_born', 'limited_english_proficiency', 'demographics',
       'population'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1877398 entries, 0 to 1877397
Data columns (total 22 columns):
 #   Column                                Dtype
---  ------                                -----
 0   date                                  object
 1   citation_issued                       bool
 2   community_area_id                     float64
 3   community_area_name                   object
 4   drug_abuse                            float64
 5   major_crime                           float64
 6   public_crime                          float64
 7   violent_crime                         float64
 8   perceived_neighborhood_violence_rate  float64
 9   perceived_neighborhood_safety_rate    float64
 10  trust_in_law_enforcement              float64
 11  trust_in_law_enforcement_rate         float64
 12  trust_in_local_government             float64
 13  trust_in_local_government_rate        float64
 14  economic_diversity_index              float64
 15  hardship_index                        float64
 16  median_household_income               float64
 17  poverty_rate                          float64
 18  foreign_born                          float64
 19  limited_english_proficiency           float64
 20  demographics                          float64
 21  population                            float64
dtypes: bool(1), float64(19), object(2)
memory usage: 302.6+ MB

In [5]:
# make a year column
df["date"] = pd.to_datetime(df["date"])
df["year"] = df["date"].dt.year
df.head()

,date,citation_issued,community_area_id,community_area_name,drug_abuse,major_crime,public_crime,violent_crime,perceived_neighborhood_violence_rate,perceived_neighborhood_safety_rate,...,trust_in_local_government_rate,economic_diversity_index,hardship_index,median_household_income,poverty_rate,foreign_born,limited_english_proficiency,demographics,population,year
0,2012-01-01,False,25.0,AUSTIN,887.076330,5212.931862,4142.0,1860.058140,39.271852,50.052980,...,39.844682,0.775025,85.469151,51826.851402,23.399157,10.704508,8.804414,5.533701,97671.110800,2012
1,2012-01-01,False,8.0,NEAR NORTH SIDE,107.618043,4637.132155,410.0,647.271573,31.535808,75.076345,...,39.185753,0.354411,3.402425,125101.326886,9.622478,18.181435,4.297681,66.267215,99292.486072,2012
2,2012-01-01,False,20.0,HERMOSA,17.999670,577.545123,257.0,150.146585,14.840824,57.122871,...,53.921078,0.798612,77.967935,70459.881153,13.674981,34.878304,36.024369,9.575501,22644.717836,2012
3,2012-01-01,False,68.0,ENGLEWOOD,155.143225,2069.136841,1908.0,802.609406,51.774635,36.410150,...,27.250549,0.728528,93.089143,32084.861861,33.435182,5.675052,5.465415,1.005840,23160.939521,2012
4,2012-01-01,False,55.0,HEGEWISCH,2.972177,252.080902,50.0,57.518202,36.200762,51.187100,...,28.253638,0.802099,68.392927,61745.599215,9.820789,14.676821,11.130220,35.767045,8767.938562,2012

In [6]:
df.tail()

,date,citation_issued,community_area_id,community_area_name,drug_abuse,major_crime,public_crime,violent_crime,perceived_neighborhood_violence_rate,perceived_neighborhood_safety_rate,...,trust_in_local_government_rate,economic_diversity_index,hardship_index,median_household_income,poverty_rate,foreign_born,limited_english_proficiency,demographics,population,year
1877393,2020-05-16,False,27.0,EAST GARFIELD PARK,349.670389,1498.367316,1292.0,542.060539,50.334442,41.773682,...,22.923965,0.732096,92.150919,39861.333805,37.256195,2.921534,1.897934,7.756904,20739.825817,2020
1877394,2020-05-16,False,32.0,LOOP,180.998603,3516.357091,199.0,432.330110,22.401325,78.562535,...,48.260009,0.303370,6.880908,119221.584097,11.145882,27.777929,4.824201,49.764161,43756.849875,2020
1877395,2020-05-16,False,32.0,LOOP,180.998603,3516.357091,199.0,432.330110,22.401325,78.562535,...,48.260009,0.303370,6.880908,119221.584097,11.145882,27.777929,4.824201,49.764161,43756.849875,2020
1877396,2020-05-16,False,23.0,HUMBOLDT PARK,635.097343,2907.857343,1814.0,933.236330,39.941668,45.670418,...,32.277557,0.781104,82.767377,58409.067093,26.772810,22.184584,21.887965,12.249829,55766.955333,2020
1877397,2020-05-16,False,24.0,WEST TOWN,124.115049,4918.215955,1078.0,682.716599,25.610812,72.962996,...,37.691627,0.445569,7.822826,141145.376335,8.113390,12.804424,7.060238,61.416808,88181.676030,2020

In [7]:
# make citation numeric and not T/F
df["citation_numeric"] = df["citation_issued"].astype(int)

In [8]:
# group by community area only
community_area_df = (
    df.groupby(["community_area_id"], as_index=False)
      .agg(
          citation_pct=("citation_numeric", "mean"),
          n_stops=("citation_numeric", "size"),
          community_area_name=("community_area_name", "first"),
          drug_abuse=("drug_abuse", "first"),
          major_crime=("major_crime", "first"),
          public_crime=("public_crime", "first"),
          violent_crime=("violent_crime", "first"),
          perceived_neighborhood_violence_rate=("perceived_neighborhood_violence_rate", "first"),
          perceived_neighborhood_safety_rate=("perceived_neighborhood_safety_rate", "first"),
          trust_in_law_enforcement=("trust_in_law_enforcement", "first"),
          trust_in_law_enforcement_rate=("trust_in_law_enforcement_rate", "first"),
          trust_in_local_government=("trust_in_local_government", "first"),
          trust_in_local_government_rate=("trust_in_local_government_rate", "first"),
          economic_diversity_index=("economic_diversity_index", "first"),
          hardship_index=("hardship_index", "first"),
          median_household_income=("median_household_income", "first"),
          limited_english_proficiency=("limited_english_proficiency", "first"),
          population=("population", "first"),
          poverty_rate=("poverty_rate", "first"),
          foreign_born=("foreign_born", "first"),
          demographics=("demographics", "first")
      )
)

community_area_df.head()

,community_area_id,citation_pct,n_stops,community_area_name,drug_abuse,major_crime,public_crime,violent_crime,perceived_neighborhood_violence_rate,perceived_neighborhood_safety_rate,...,trust_in_local_government,trust_in_local_government_rate,economic_diversity_index,hardship_index,median_household_income,limited_english_proficiency,population,poverty_rate,foreign_born,demographics
0,1.0,0.528444,14291,ROGERS PARK,52.430941,1760.907198,495.0,298.203142,34.801957,73.174568,...,19500.0,36.961025,0.734804,52.924704,63293.406981,16.137010,54023.514047,17.476965,25.380584,44.902568
1,2.0,0.743763,16313,WEST RIDGE,22.948027,1581.360787,339.0,266.247177,17.063957,67.910625,...,24500.0,48.332844,0.767896,76.071658,71334.903966,24.395617,78390.308219,19.410326,38.399181,39.876283
2,3.0,0.541228,20435,UPTOWN,24.147636,1957.368091,373.0,294.201256,27.509064,77.214482,...,19500.0,40.778530,0.623804,35.406658,73109.526853,13.238442,54490.992635,18.635561,24.058594,51.593893
3,4.0,0.960499,10253,LINCOLN SQUARE,26.977910,1276.689147,133.0,230.513409,11.108168,86.937593,...,17100.0,58.441246,0.636896,23.192702,91363.093539,12.868333,41565.112883,9.492826,21.795044,62.078651
4,5.0,0.981344,4449,NORTH CENTER,12.453722,1215.406535,101.0,162.385518,13.120720,90.502351,...,11000.0,47.104718,0.433606,4.303042,147701.197916,3.040809,36047.308966,5.046812,9.726982,73.568145

In [9]:
community_area_df.tail()

,community_area_id,citation_pct,n_stops,community_area_name,drug_abuse,major_crime,public_crime,violent_crime,perceived_neighborhood_violence_rate,perceived_neighborhood_safety_rate,...,trust_in_local_government,trust_in_local_government_rate,economic_diversity_index,hardship_index,median_household_income,limited_english_proficiency,population,poverty_rate,foreign_born,demographics
71,72.0,0.523582,3562,BEVERLY,26.177839,744.658954,93.0,144.383486,19.181235,79.534107,...,7200.0,52.791065,0.572223,32.222612,130925.633113,0.184719,19553.608885,5.844943,3.367923,57.045465
72,73.0,0.755636,7984,WASHINGTON HEIGHTS,44.740050,1148.975359,914.0,316.849843,22.791276,61.847047,...,9100.0,41.405838,0.783021,70.853255,64755.743009,3.376382,24755.828995,16.245325,3.973536,1.464242
73,74.0,0.828912,754,MOUNT GREENWOOD,5.412940,214.784698,28.0,29.612760,23.759855,81.779584,...,4300.0,34.068847,0.568886,26.431421,112562.284278,0.976591,19064.084350,5.374588,1.857033,82.073894
74,75.0,0.152932,22546,MORGAN PARK,26.865680,762.732697,376.0,148.115441,29.431384,79.521373,...,7300.0,50.856121,0.736286,60.570537,72941.346928,0.942856,21410.012942,17.910979,4.508224,28.305440
75,77.0,0.555805,12893,EDGEWATER,20.080216,1505.430172,211.0,237.259845,17.863914,76.889933,...,28900.0,53.508582,0.650356,40.406505,75774.409686,12.452153,56573.000669,16.394075,25.941233,51.631499

In [10]:
community_area_df.shape

(76, 22)

In [11]:
# save datatset
community_area_df.to_csv("community_area_data.csv", index=False)